openapi: 3.0.3
info:
  title: Liability Engine Customer Data Handler
  description: |-
    The Liability Engine Customer Data Handler (LECDH) exposes a HTTP REST API to control the default customer stake factor to be used on the liability flow.


  termsOfService: http://swagger.io/terms/
  contact:
    email: sports.area51@fanduel.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
tags:
  - name: Customer liability configurations
    description: Everything about the customer liability configurations
paths:
  /customer/stakeFactor:
    put:
      tags:
        - customer
      summary: Updates the customer default stake factor that will be applied to every customer that doesn't have stake factor defined.
      operationId: updateCustomerDefaultStakeFactor 
      requestBody:
        description: Created customer object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DefaultCustomerStakeFactor'
      responses:
        '204':
          description: The customer default stake factor was updated successfully.
  
  /customer/{accountid}/hierarchyThreshold:
    put:
      tags:
        - customer
      summary: Adds or updates the customer hierarchy threshold for given Subclass or EventType
      description: Adds or updates the customer threshold for given hierarchy (Subclass or EventType)
      operationId: updateCustomerHierarchythreshold
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/AccountId'
      requestBody: 
        description: Add customer liability threshold
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerHierarchyThreshold'
      responses:
        '204':
          description: updated the customer  hierarchy threshold successfully.
    delete:
      tags: 
        - customer
      summary: Deletes the customer hierarchy threshold for given Subclass or EventType
      description: Deletes the customer hierarchy threshold for a given hierarchy (Subclass or Event)
      operationId: deleteCustomerHierarchyThreshold
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/AccountId'      
        - name: hierarchyType
          in: query 
          description: Hierarchy Type
          required: true
          schema:
            $ref: '#/components/schemas/HierarchyType'
        - name: hierarchyId
          in: query 
          description: Hierarchy Id
          required: true
          schema:
            $ref: '#/components/schemas/HierarchyId'
      responses:
        '204':
          description: Deleted the customer hierarchy threshold successfully.
      


components:
  schemas:
    DefaultCustomerStakeFactor:
      type: object
      properties:
        stakeFactor:
          type: number
          format: float
          example: 1.1
    
    CustomerHierarchyThreshold:
      type: object
      properties:    
        hierarchyType:
          $ref: '#/components/schemas/HierarchyType'
        hierarchyId:
          $ref: '#/components/schemas/HierarchyId'    
        threshold:      
          type: number
          format: float
          minimum: 0 
          description: the threshold to be applied to the customer parlays by hierarchy type
    
    AccountId:
      type: string
      example: "123"

    HierarchyId:
      type: string
      example: "17"

    HierarchyType:
      type: string
      enum:
        - SUBCLASS
        - EVENT_TYPE        
    